[window]
padding = { x = 0, y = 0 }
opacity = 1

[font]
normal = { family = "CodeNewRoman Nerd Font Mono", style = "Regular" }
bold = { family = "CodeNewRoman Nerd Font Mono", style = "bold" }
italic = { family = "CodeNewRoman Nerd Font Mono", style = "italic" }
bold_italic = { family = "CodeNewRoman Nerd Font Mono", style = "bold italic" }

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
style = { shape = "Beam", blinking = "On" }

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"
